#!/usr/bin/env python3
"""
gen_font.py  —  Generate LVGL font (.c) files from TrueType fonts.

Setup (once):
    npm install -g lv_font_conv

Usage:
    python3 gen_font.py                  # generate the full recommended set
    python3 gen_font.py --font fonts/JetBrainsMono-Bold.ttf --sizes 20 24 28

Output .c files land in src/fonts/ and are ready to use immediately:
    LV_FONT_DECLARE(JetBrainsMono_Bold_24);
    lv_obj_set_style_text_font(label, &JetBrainsMono_Bold_24, 0);

Character range included in every font:
    0x20–0x7E   ASCII printable
    0x80–0xFF   Latin-1 Supplement  (é à ö ü ç °  etc.)
    0x100–0x17F Latin Extended-A    (ā ē ī ō ū  etc.)
"""

import argparse
import subprocess
import sys
from pathlib import Path

# ── Recommended font set ──────────────────────────────────────────────────────
# Edit this table to change what gets generated by the no-argument invocation.
#
# Each entry: (ttf_path, [sizes])
#   Regular  → small UI text, status labels
#   Medium   → body text, value labels
#   Bold     → headlines, numeric readouts, emphasis

FONT_SETS = [
    ("fonts/JetBrainsMono-Regular.ttf", [12, 14, 16, 18, 20, 24, 60]),
    ("fonts/JetBrainsMono-Medium.ttf",  [16, 20, 24, 28, 32, 60]),
    ("fonts/JetBrainsMono-Bold.ttf",    [16, 20, 24, 28, 32, 36, 48, 60]),
]
# ─────────────────────────────────────────────────────────────────────────────

LV_FONT_CONV = "lv_font_conv"
OUT_DIR = Path("src/fonts")
CHAR_RANGE = "0x20-0x7E,0x80-0xFF,0x0100-0x017F"


def gen(font_file: Path, size: int) -> bool:
    variant = font_file.stem.replace("-", "_")   # e.g. JetBrainsMono_Bold
    out_name = f"{variant}_{size}"
    out_file = OUT_DIR / f"{out_name}.c"

    cmd = [
        LV_FONT_CONV,
        "--font",   str(font_file),
        "--size",   str(size),
        "--bpp",    "4",
        "--format", "lvgl",
        "--range",  CHAR_RANGE,
        "-o",       str(out_file),
        "--no-compress",
    ]

    result = subprocess.run(cmd, capture_output=True, text=True)

    if result.returncode != 0:
        err = result.stderr.strip()
        print(f"  ERROR: {err}")
        if "not found" in err or result.returncode == 127:
            print("  Hint: npm install -g lv_font_conv")
        return False

    size_kb = out_file.stat().st_size / 1024
    print(f"  {out_file}  ({size_kb:.1f} KB)   →  &{out_name}")
    return True


def run_set(font_path: str, sizes: list[int]):
    font_file = Path(font_path)
    if not font_file.exists():
        print(f"\nSKIP — file not found: {font_file}")
        return
    print(f"\n{font_file.name}  ({', '.join(str(s) for s in sizes)} pt)")
    for size in sizes:
        gen(font_file, size)


def main():
    parser = argparse.ArgumentParser(description="Generate LVGL .c font files.")
    parser.add_argument("--font",  help="Path to a .ttf file")
    parser.add_argument("--sizes", nargs="+", type=int, help="Point sizes to generate")
    args = parser.parse_args()

    OUT_DIR.mkdir(parents=True, exist_ok=True)

    if args.font:
        # Single-font mode
        if not args.sizes:
            print("ERROR: --sizes required when --font is specified.")
            sys.exit(1)
        run_set(args.font, args.sizes)
    else:
        # Batch mode — generate the full recommended set
        print("Generating recommended font set …")
        for font_path, sizes in FONT_SETS:
            run_set(font_path, sizes)

    print("\nDone. Declare fonts in your .cpp with:")
    print("  LV_FONT_DECLARE(<font_name>);")
    print("Use as:  lv_obj_set_style_text_font(obj, &<font_name>, 0);")


if __name__ == "__main__":
    main()
