#!/usr/bin/env python3
"""Generate 70x70 legend-only aircraft mask headers (heading 0 only).

Each output file contains a single mask for the north-facing icon.
Flash cost: 12 × 630 bytes = 7 560 bytes total — negligible.

Usage:
    python3 tools/generate_legend_icons.py

Reads PNGs from the shared 360_zoomed source tree in ESP32-ADSB_Companion.
Writes headers to src/aircraft/assets_legend/.
"""

from pathlib import Path
from PIL import Image

ROOT   = Path(__file__).resolve().parents[1]
SOURCE = (
    ROOT.parent
    / "ESP32-ADSB_Companion"
    / "pythonTools"
    / "ForDevelopmentOnly"
    / "iconsBuilder"
    / "360_zoomed"
)
OUTPUT = ROOT / "src" / "aircraft" / "assets_legend"

SIZE             = 70
ALPHA_THRESHOLD  = 128
HEADING          = 0   # north-facing; file name is "000.png"
CATEGORIES       = ("A0", "A1", "A2", "A3", "A4", "A5", "A6", "A7",
                    "B0", "B1", "B2", "NA")


def pack_mask(path: Path, size: int) -> bytes:
    img  = Image.open(path).convert("RGBA").resize((size, size), Image.Resampling.LANCZOS)
    alpha  = img.getchannel("A")
    stride = (size + 7) // 8
    packed = bytearray(size * stride)
    for y in range(size):
        for x in range(size):
            if alpha.getpixel((x, y)) >= ALPHA_THRESHOLD:
                packed[y * stride + x // 8] |= 0x80 >> (x & 7)
    return bytes(packed)


def format_bytes(name: str, data: bytes) -> str:
    lines = [f"static const uint8_t {name}[{len(data)}] PROGMEM = {{"]
    for offset in range(0, len(data), 16):
        chunk = data[offset: offset + 16]
        lines.append("  " + ", ".join(f"0x{v:02X}" for v in chunk) + ",")
    lines.append("};")
    return "\n".join(lines)


def generate(category: str) -> None:
    src = SOURCE / category / f"{HEADING:03d}.png"
    if not src.exists():
        raise FileNotFoundError(src)

    data   = pack_mask(src, SIZE)
    prefix = f"{category}leg"
    stride = (SIZE + 7) // 8

    header = "\n".join((
        "#pragma once",
        "#include <stdint.h>",
        "#include <pgmspace.h>",
        "",
        "// Generated by tools/generate_legend_icons.py",
        f"// Category {category} — single 70x70 mask, heading 0 (north)",
        "",
        f"static const uint16_t {prefix}_w              = {SIZE};",
        f"static const uint16_t {prefix}_h              = {SIZE};",
        f"static const uint16_t {prefix}_stride         = {stride};",
        f"static const uint16_t {prefix}_bytes_per_mask = {len(data)};",
        "",
        format_bytes(f"{prefix}_masks", data),
        "",
    ))

    OUTPUT.mkdir(parents=True, exist_ok=True)
    dest = OUTPUT / f"{prefix}.h"
    dest.write_text(header, encoding="utf-8")
    print(f"{category}: {dest.relative_to(ROOT)}  ({len(data)} bytes)")


def main() -> None:
    for cat in CATEGORIES:
        generate(cat)
    print(f"\nTotal PROGMEM: {12 * SIZE * ((SIZE + 7) // 8)} bytes")


if __name__ == "__main__":
    main()
