#!/usr/bin/env python3
"""Generate 40x40 aircraft mask headers from the existing 360 PNG frames."""

from pathlib import Path

from PIL import Image


ROOT = Path(__file__).resolve().parents[1]
SOURCE = (
    ROOT
    / "ADSB"
    / "pythonTools"
    / "ForDevelopmentOnly"
    / "iconsBuilder"
    / "360_zoomed"
)
OUTPUT = ROOT / "src" / "aircraft" / "assets40"

FINAL_SIZE = 40
ALPHA_THRESHOLD = 128
CATEGORIES = ("A0", "A1", "A2", "A3", "A4", "A5", "A6", "A7",
              "B0", "B1", "B2", "NA")


def pack_mask(image: Image.Image) -> bytes:
    image = image.convert("RGBA").resize(
        (FINAL_SIZE, FINAL_SIZE), Image.Resampling.LANCZOS
    )
    alpha = image.getchannel("A")
    stride = (FINAL_SIZE + 7) // 8
    packed = bytearray(FINAL_SIZE * stride)

    for y in range(FINAL_SIZE):
        for x in range(FINAL_SIZE):
            if alpha.getpixel((x, y)) >= ALPHA_THRESHOLD:
                packed[y * stride + x // 8] |= 0x80 >> (x & 7)
    return bytes(packed)


def format_bytes(name: str, data: bytes) -> str:
    lines = [f"static const uint8_t {name}[{len(data)}] PROGMEM = {{"]
    for offset in range(0, len(data), 16):
        chunk = data[offset : offset + 16]
        lines.append("  " + ", ".join(f"0x{value:02X}" for value in chunk) + ",")
    lines.append("};")
    return "\n".join(lines)


def generate_category(category: str) -> None:
    source_dir = SOURCE / category
    frames = []
    for heading in range(360):
        path = source_dir / f"{heading:03d}.png"
        if not path.exists():
            raise FileNotFoundError(path)
        frames.append(pack_mask(Image.open(path)))

    blob = b"".join(frames)
    prefix = f"{category}40"
    stride = (FINAL_SIZE + 7) // 8
    bytes_per_mask = FINAL_SIZE * stride
    header = "\n".join(
        (
            "#pragma once",
            "#include <stdint.h>",
            "#include <pgmspace.h>",
            "",
            "// Generated by tools/generate_aircraft_40.py",
            f"// Source category: {category}",
            "// Format: 40x40 1-bit masks, 360 headings",
            "",
            f"static const uint16_t {prefix}_w = {FINAL_SIZE};",
            f"static const uint16_t {prefix}_h = {FINAL_SIZE};",
            f"static const uint16_t {prefix}_stride = {stride};",
            f"static const uint16_t {prefix}_bytes_per_mask = {bytes_per_mask};",
            "",
            format_bytes(f"{prefix}_masks", blob),
            "",
        )
    )

    OUTPUT.mkdir(parents=True, exist_ok=True)
    destination = OUTPUT / f"{prefix}_360.h"
    destination.write_text(header, encoding="utf-8")
    print(f"{category}: {destination.relative_to(ROOT)} ({len(blob)} bytes)")


def main() -> None:
    for category in CATEGORIES:
        generate_category(category)


if __name__ == "__main__":
    main()
